name: 'Link validation'
description: 'Validates URLs and local file references in Markdown files'
inputs:
  log-level:
    description: 'Controls verbosity (debug, info, warn, error)'
    default: "info"
  file-mask:
    description: "Comma-separated file patterns to scan. Only markdown is supported in the current version"
    default: "*.md"
  pat:
    description: "GitHub.com personal access token. Optional. Used to avoid rate limiting"
    default: ""
  corp-url:
    description: "GitHub Enterprise base URL, for example, https://github.mycorp.com"
    default: ""
  corp-pat:
    description: >
      GitHub Enterprise personal access token.
      The PAT needs read access to repositories referenced in your documentation.
    default: ""
runs:
  using: 'composite'
  steps:
    - name: Link validation
      shell: bash
      env:
        LV_LOG_LEVEL: ${{ inputs.log-level }}
        LV_FILE_MASKS: ${{ inputs.file-mask }}
        LV_PAT: ${{ inputs.pat }}
        LV_CORP_PAT: ${{ inputs.corp-pat }}
        LV_CORP_URL: ${{ inputs.corp-url }}
        DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator
        DOCKER_VALIDATOR_VERSION: 0.21.0
      run: |
        DOCKER_ENV_ARGS=""
        for var in $(env | grep '^LV_' | cut -d'=' -f1); do
          DOCKER_ENV_ARGS="$DOCKER_ENV_ARGS -e $var"
        done
        
        docker run --rm \
               $DOCKER_ENV_ARGS \
               -v "${{ github.workspace }}:/work" \
               -w /work \
               ${{ env.DOCKER_VALIDATOR }}:${{ github.ref_name }}
