name: 'Link validation'
description: 'Validates URLs and local file references in Markdown files'
author: your-ko
branding:
  icon: 'link'
  color: 'blue'
inputs:
  logLevel:
    description: 'Controls verbosity (debug, info, warn, error).'
    default: "info"
  fileMasks:
    description: "Comma-separated file patterns to scan."
    default: "*.md"
  pat:
    description: "GitHub.com personal access token. Optional. Used to avoid rate limiting."
    default: ""
  corpUrl:
    description: "GitHub Enterprise base URL, for example, https://github.mycorp.com"
    default: ""
  corpPat:
    description: "GitHub Enterprise personal access token.  The PAT needs read access to repositories referenced in your documentation."
    default: ""
  ddApiKey:
    description: "Datadog API key."
    default: ""
  ddAppKey:
    description: "Datadog APP key."
    default: ""
  ignoredDomains:
    description: "Comma separated list of domains or their parts that should be ignored during validation."
    default: ""
  files:
    description: "Comma separated list of files to validate."
    default: ""
  timeout:
    description: "HTTP request timeout."
    default: "5s"
  redirects:
    description: "HTTP redirects number."
    default: "3"
  exlude:
    description: "Comma separated list of files or folders to exclude from validation."
    default: ""
  lookupPath:
    description: "A path to look for the files up."
    default: "./"
  vaultTokens:
    description: "Comma-separated vault name:token pairs, e.g., 'pre:token1,prod:token2'"
    default: ""
runs:
  using: 'composite'
  steps:
    - name: Link validation
      shell: bash
      env:
        DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator
        DOCKER_VALIDATOR_VERSION: 1.20.0
      run: |
        # Parse vault tokens (comma-separated name:token pairs) and create environment variables
        vault_env_vars=""
        if [[ -n "${{ inputs.vault-tokens }}" ]]; then
        # Split by commas and process each name:token pair
        IFS=',' read -ra VAULT_PAIRS <<< "${{ inputs.vault-tokens }}"
        for pair in "${VAULT_PAIRS[@]}"; do
        # Trim whitespace from pair
        pair=$(echo "$pair" | xargs)
        if [[ "$pair" =~ ^([^:]+):(.+)$ ]]; then
        vault_name="${BASH_REMATCH[1]}"
        vault_token="${BASH_REMATCH[2]}"
        # Convert vault name to uppercase for environment variable
        vault_key="VAULT_TOKEN_$(echo "$vault_name" | tr '[:lower:]' '[:upper:]')"
        vault_env_vars="$vault_env_vars -e '$vault_key=$vault_token'"
        fi
        done
        fi

        # Run docker with vault environment variables
        eval "docker run --rm \
          -e LOG_LEVEL=${{ inputs.logLevel }} \
          -e 'FILE_MASKS=${{ inputs.fileMasks }}' \
          -e 'PAT=${{ inputs.pat }}' \
          -e 'CORP_PAT=${{ inputs.corpPat }}' \
          -e 'DD_API_KEY=${{ inputs.ddApiKey }}' \
          -e 'DD_APP_KEY=${{ inputs.ddAppKey }}' \
          -e 'CORP_URL=${{ inputs.corpUrl }}' \
          -e 'FILES=${{ inputs.files }}' \
          -e 'TIMEOUT=${{ inputs.timeout }}' \
          -e 'IGNORED_DOMAINS=${{ inputs.ignoredDomains }}' \
          -e 'REDIRECTS=${{ inputs.redirects }}' \
          -e 'EXCLUDE=${{ inputs.exlude }}' \
          -e 'lookupPath=${{ inputs.lookupPath }}' \
          $vault_env_vars \
          -v "${{ github.workspace }}:/work" \
          -w /work \
          ${DOCKER_VALIDATOR}:${DOCKER_VALIDATOR_VERSION}"
