name: 'Link validation'
description: 'Validates URLs and local file references in Markdown files'
author: your-ko
branding:
  icon: 'link'
  color: 'blue'
inputs:
  logLevel:
    description: 'Controls verbosity (debug, info, warn, error).'
    default: "info"
  fileMasks:
    description: "Comma-separated file patterns to scan."
    default: "*.md"
  pat:
    description: "GitHub.com personal access token. Optional. Used to avoid rate limiting."
    default: ""
  corpUrl:
    description: "GitHub Enterprise base URL, for example, https://github.mycorp.com"
    default: ""
  corpPat:
    description: "GitHub Enterprise personal access token.  The PAT needs read access to repositories referenced in your documentation."
    default: ""
  ddApiKey:
    description: "Datadog API key."
    default: ""
  ddAppKey:
    description: "Datadog APP key."
    default: ""
  ignore:
    description: "Comma separated list of domains or their parts that should be ignored during validation."
    default: ""
  files:
    description: "Comma separated list of files to validate."
    default: ""
  timeout:
    description: "HTTP request timeout."
    default: "5s"
  redirects:
    description: "HTTP redirects number."
    default: "3"
  exlude:
    description: "Comma separated list of files or folders to exclude from validation."
    default: ""
  lookupPath:
    description: "A path to look for the files up."
    default: "./"
runs:
  using: 'composite'
  steps:
    - name: Link validation
      shell: bash
      env:
        DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator
        DOCKER_VALIDATOR_VERSION: 2.0.0
      run: |
        docker run --rm \
          -e LOG_LEVEL=${{ inputs.logLevel }} \
          -e 'FILE_MASKS=${{ inputs.fileMasks }}' \
          -e 'PAT=${{ inputs.pat }}' \
          -e 'CORP_PAT=${{ inputs.corpPat }}' \
          -e 'DD_API_KEY=${{ inputs.ddApiKey }}' \
          -e 'DD_APP_KEY=${{ inputs.ddAppKey }}' \
          -e 'CORP_URL=${{ inputs.corpUrl }}' \
          -e 'FILES=${{ inputs.files }}' \
          -e 'TIMEOUT=${{ inputs.timeout }}' \
          -e 'IGNORE=${{ inputs.ignore }}' \
          -e 'REDIRECTS=${{ inputs.redirects }}' \
          -e 'EXCLUDE=${{ inputs.exlude }}' \
          -e 'lookupPath=${{ inputs.lookupPath }}' \
          -v "${{ github.workspace }}:/work" \
          -w /work \
          ${DOCKER_VALIDATOR}:${DOCKER_VALIDATOR_VERSION}
