name: 'Link validation'
description: 'Validates URLs and local file references in Markdown files'
author: your-ko
branding:
  icon: 'link'
  color: 'blue'
inputs:
  log-level:
    description: 'Controls verbosity (debug, info, warn, error).'
    default: "info"
  file-mask:
    description: "Comma-separated file patterns to scan. Only markdown is supported in the current version."
    default: "*.md"
  pat:
    description: "GitHub.com personal access token. Optional. Used to avoid rate limiting."
    default: ""
  corp-url:
    description: "GitHub Enterprise base URL, for example, https://github.mycorp.com"
    default: ""
  corp-pat:
    description: "GitHub Enterprise personal access token.  The PAT needs read access to repositories referenced in your documentation."
    default: ""
  ignored-domains:
    description: "Comma separated list of domains or their parts that should be ignored during validation."
    default: ""
  files:
    description: "Comma separated list of files to validate."
    default: ""
  timeout:
    description: "HTTP request timeout."
    default: "3s"
runs:
  using: 'composite'
  steps:
    - name: Link validation
      shell: bash
      run: |
        docker run --rm \
          -e LOG_LEVEL=${{ inputs.log-level }} \
          -e 'FILE_MASKS=${{ inputs.file-mask }}' \
          -e 'PAT=${{ inputs.pat }}' \
          -e 'CORP_PAT=${{ inputs.corp-pat }}' \
          -e CORP_URL=${{ inputs.corp-url }} \
          -e FILES=${{ inputs.files }} \
          -e TIMEOUT=${{ inputs.timeout }} \
          -e IGNORED_DOMAINS=${{ inputs.ignored-domains }} \
          -v "${{ github.workspace }}:/work" \
          -w /work \
          ghcr.io/your-ko/link-validator:1.10.0
