// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vault

import (
	"context"

	"github.com/hashicorp/vault-client-go"
	mock "github.com/stretchr/testify/mock"
)

// newMockvaultClient creates a new instance of mockvaultClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockvaultClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockvaultClient {
	mock := &mockvaultClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockvaultClient is an autogenerated mock type for the vaultClient type
type mockvaultClient struct {
	mock.Mock
}

type mockvaultClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockvaultClient) EXPECT() *mockvaultClient_Expecter {
	return &mockvaultClient_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type mockvaultClient
func (_mock *mockvaultClient) List(ctx context.Context, path string, options ...vault.RequestOption) (*vault.Response[map[string]interface{}], error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, path, options)
	} else {
		tmpRet = _mock.Called(ctx, path)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *vault.Response[map[string]interface{}]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...vault.RequestOption) (*vault.Response[map[string]interface{}], error)); ok {
		return returnFunc(ctx, path, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...vault.RequestOption) *vault.Response[map[string]interface{}]); ok {
		r0 = returnFunc(ctx, path, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.Response[map[string]interface{}])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...vault.RequestOption) error); ok {
		r1 = returnFunc(ctx, path, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockvaultClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockvaultClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - options ...vault.RequestOption
func (_e *mockvaultClient_Expecter) List(ctx interface{}, path interface{}, options ...interface{}) *mockvaultClient_List_Call {
	return &mockvaultClient_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, path}, options...)...)}
}

func (_c *mockvaultClient_List_Call) Run(run func(ctx context.Context, path string, options ...vault.RequestOption)) *mockvaultClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []vault.RequestOption
		var variadicArgs []vault.RequestOption
		if len(args) > 2 {
			variadicArgs = args[2].([]vault.RequestOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockvaultClient_List_Call) Return(response *vault.Response[map[string]interface{}], err error) *mockvaultClient_List_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *mockvaultClient_List_Call) RunAndReturn(run func(ctx context.Context, path string, options ...vault.RequestOption) (*vault.Response[map[string]interface{}], error)) *mockvaultClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type mockvaultClient
func (_mock *mockvaultClient) Read(ctx context.Context, path string, options ...vault.RequestOption) (*vault.Response[map[string]interface{}], error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, path, options)
	} else {
		tmpRet = _mock.Called(ctx, path)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *vault.Response[map[string]interface{}]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...vault.RequestOption) (*vault.Response[map[string]interface{}], error)); ok {
		return returnFunc(ctx, path, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...vault.RequestOption) *vault.Response[map[string]interface{}]); ok {
		r0 = returnFunc(ctx, path, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.Response[map[string]interface{}])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...vault.RequestOption) error); ok {
		r1 = returnFunc(ctx, path, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockvaultClient_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mockvaultClient_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - options ...vault.RequestOption
func (_e *mockvaultClient_Expecter) Read(ctx interface{}, path interface{}, options ...interface{}) *mockvaultClient_Read_Call {
	return &mockvaultClient_Read_Call{Call: _e.mock.On("Read",
		append([]interface{}{ctx, path}, options...)...)}
}

func (_c *mockvaultClient_Read_Call) Run(run func(ctx context.Context, path string, options ...vault.RequestOption)) *mockvaultClient_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []vault.RequestOption
		var variadicArgs []vault.RequestOption
		if len(args) > 2 {
			variadicArgs = args[2].([]vault.RequestOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockvaultClient_Read_Call) Return(response *vault.Response[map[string]interface{}], err error) *mockvaultClient_Read_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *mockvaultClient_Read_Call) RunAndReturn(run func(ctx context.Context, path string, options ...vault.RequestOption) (*vault.Response[map[string]interface{}], error)) *mockvaultClient_Read_Call {
	_c.Call.Return(run)
	return _c
}
