// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dd

import (
	"context"
	"net/http"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadog"
	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV1"
	mock "github.com/stretchr/testify/mock"
)

// newMockclient creates a new instance of mockclient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclient {
	mock := &mockclient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclient is an autogenerated mock type for the client type
type mockclient struct {
	mock.Mock
}

type mockclient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclient) EXPECT() *mockclient_Expecter {
	return &mockclient_Expecter{mock: &_m.Mock}
}

// getDDClient provides a mock function for the type mockclient
func (_mock *mockclient) getDDClient() *datadog.APIClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getDDClient")
	}

	var r0 *datadog.APIClient
	if returnFunc, ok := ret.Get(0).(func() *datadog.APIClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datadog.APIClient)
		}
	}
	return r0
}

// mockclient_getDDClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDDClient'
type mockclient_getDDClient_Call struct {
	*mock.Call
}

// getDDClient is a helper method to define mock.On call
func (_e *mockclient_Expecter) getDDClient() *mockclient_getDDClient_Call {
	return &mockclient_getDDClient_Call{Call: _e.mock.On("getDDClient")}
}

func (_c *mockclient_getDDClient_Call) Run(run func()) *mockclient_getDDClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclient_getDDClient_Call) Return(aPIClient *datadog.APIClient) *mockclient_getDDClient_Call {
	_c.Call.Return(aPIClient)
	return _c
}

func (_c *mockclient_getDDClient_Call) RunAndReturn(run func() *datadog.APIClient) *mockclient_getDDClient_Call {
	_c.Call.Return(run)
	return _c
}

// getDashboard provides a mock function for the type mockclient
func (_mock *mockclient) getDashboard(ctx context.Context, dashboardId string) (datadogV1.Dashboard, *http.Response, error) {
	ret := _mock.Called(ctx, dashboardId)

	if len(ret) == 0 {
		panic("no return value specified for getDashboard")
	}

	var r0 datadogV1.Dashboard
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (datadogV1.Dashboard, *http.Response, error)); ok {
		return returnFunc(ctx, dashboardId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) datadogV1.Dashboard); ok {
		r0 = returnFunc(ctx, dashboardId)
	} else {
		r0 = ret.Get(0).(datadogV1.Dashboard)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *http.Response); ok {
		r1 = returnFunc(ctx, dashboardId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, dashboardId)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockclient_getDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDashboard'
type mockclient_getDashboard_Call struct {
	*mock.Call
}

// getDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboardId string
func (_e *mockclient_Expecter) getDashboard(ctx interface{}, dashboardId interface{}) *mockclient_getDashboard_Call {
	return &mockclient_getDashboard_Call{Call: _e.mock.On("getDashboard", ctx, dashboardId)}
}

func (_c *mockclient_getDashboard_Call) Run(run func(ctx context.Context, dashboardId string)) *mockclient_getDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockclient_getDashboard_Call) Return(dashboard datadogV1.Dashboard, response *http.Response, err error) *mockclient_getDashboard_Call {
	_c.Call.Return(dashboard, response, err)
	return _c
}

func (_c *mockclient_getDashboard_Call) RunAndReturn(run func(ctx context.Context, dashboardId string) (datadogV1.Dashboard, *http.Response, error)) *mockclient_getDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// getDashboardList provides a mock function for the type mockclient
func (_mock *mockclient) getDashboardList(ctx context.Context, listId int64) (datadogV1.DashboardList, *http.Response, error) {
	ret := _mock.Called(ctx, listId)

	if len(ret) == 0 {
		panic("no return value specified for getDashboardList")
	}

	var r0 datadogV1.DashboardList
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (datadogV1.DashboardList, *http.Response, error)); ok {
		return returnFunc(ctx, listId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) datadogV1.DashboardList); ok {
		r0 = returnFunc(ctx, listId)
	} else {
		r0 = ret.Get(0).(datadogV1.DashboardList)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) *http.Response); ok {
		r1 = returnFunc(ctx, listId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = returnFunc(ctx, listId)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockclient_getDashboardList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDashboardList'
type mockclient_getDashboardList_Call struct {
	*mock.Call
}

// getDashboardList is a helper method to define mock.On call
//   - ctx context.Context
//   - listId int64
func (_e *mockclient_Expecter) getDashboardList(ctx interface{}, listId interface{}) *mockclient_getDashboardList_Call {
	return &mockclient_getDashboardList_Call{Call: _e.mock.On("getDashboardList", ctx, listId)}
}

func (_c *mockclient_getDashboardList_Call) Run(run func(ctx context.Context, listId int64)) *mockclient_getDashboardList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockclient_getDashboardList_Call) Return(dashboardList datadogV1.DashboardList, response *http.Response, err error) *mockclient_getDashboardList_Call {
	_c.Call.Return(dashboardList, response, err)
	return _c
}

func (_c *mockclient_getDashboardList_Call) RunAndReturn(run func(ctx context.Context, listId int64) (datadogV1.DashboardList, *http.Response, error)) *mockclient_getDashboardList_Call {
	_c.Call.Return(run)
	return _c
}

// getMonitor provides a mock function for the type mockclient
func (_mock *mockclient) getMonitor(ctx context.Context, monitorId int64, o ...datadogV1.GetMonitorOptionalParameters) (datadogV1.Monitor, *http.Response, error) {
	var tmpRet mock.Arguments
	if len(o) > 0 {
		tmpRet = _mock.Called(ctx, monitorId, o)
	} else {
		tmpRet = _mock.Called(ctx, monitorId)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for getMonitor")
	}

	var r0 datadogV1.Monitor
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...datadogV1.GetMonitorOptionalParameters) (datadogV1.Monitor, *http.Response, error)); ok {
		return returnFunc(ctx, monitorId, o...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...datadogV1.GetMonitorOptionalParameters) datadogV1.Monitor); ok {
		r0 = returnFunc(ctx, monitorId, o...)
	} else {
		r0 = ret.Get(0).(datadogV1.Monitor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, ...datadogV1.GetMonitorOptionalParameters) *http.Response); ok {
		r1 = returnFunc(ctx, monitorId, o...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, ...datadogV1.GetMonitorOptionalParameters) error); ok {
		r2 = returnFunc(ctx, monitorId, o...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockclient_getMonitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getMonitor'
type mockclient_getMonitor_Call struct {
	*mock.Call
}

// getMonitor is a helper method to define mock.On call
//   - ctx context.Context
//   - monitorId int64
//   - o ...datadogV1.GetMonitorOptionalParameters
func (_e *mockclient_Expecter) getMonitor(ctx interface{}, monitorId interface{}, o ...interface{}) *mockclient_getMonitor_Call {
	return &mockclient_getMonitor_Call{Call: _e.mock.On("getMonitor",
		append([]interface{}{ctx, monitorId}, o...)...)}
}

func (_c *mockclient_getMonitor_Call) Run(run func(ctx context.Context, monitorId int64, o ...datadogV1.GetMonitorOptionalParameters)) *mockclient_getMonitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []datadogV1.GetMonitorOptionalParameters
		var variadicArgs []datadogV1.GetMonitorOptionalParameters
		if len(args) > 2 {
			variadicArgs = args[2].([]datadogV1.GetMonitorOptionalParameters)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockclient_getMonitor_Call) Return(monitor datadogV1.Monitor, response *http.Response, err error) *mockclient_getMonitor_Call {
	_c.Call.Return(monitor, response, err)
	return _c
}

func (_c *mockclient_getMonitor_Call) RunAndReturn(run func(ctx context.Context, monitorId int64, o ...datadogV1.GetMonitorOptionalParameters) (datadogV1.Monitor, *http.Response, error)) *mockclient_getMonitor_Call {
	_c.Call.Return(run)
	return _c
}

// listMonitors provides a mock function for the type mockclient
func (_mock *mockclient) listMonitors(ctx context.Context, o ...datadogV1.ListMonitorsOptionalParameters) ([]datadogV1.Monitor, *http.Response, error) {
	var tmpRet mock.Arguments
	if len(o) > 0 {
		tmpRet = _mock.Called(ctx, o)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for listMonitors")
	}

	var r0 []datadogV1.Monitor
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...datadogV1.ListMonitorsOptionalParameters) ([]datadogV1.Monitor, *http.Response, error)); ok {
		return returnFunc(ctx, o...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...datadogV1.ListMonitorsOptionalParameters) []datadogV1.Monitor); ok {
		r0 = returnFunc(ctx, o...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datadogV1.Monitor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...datadogV1.ListMonitorsOptionalParameters) *http.Response); ok {
		r1 = returnFunc(ctx, o...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ...datadogV1.ListMonitorsOptionalParameters) error); ok {
		r2 = returnFunc(ctx, o...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockclient_listMonitors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'listMonitors'
type mockclient_listMonitors_Call struct {
	*mock.Call
}

// listMonitors is a helper method to define mock.On call
//   - ctx context.Context
//   - o ...datadogV1.ListMonitorsOptionalParameters
func (_e *mockclient_Expecter) listMonitors(ctx interface{}, o ...interface{}) *mockclient_listMonitors_Call {
	return &mockclient_listMonitors_Call{Call: _e.mock.On("listMonitors",
		append([]interface{}{ctx}, o...)...)}
}

func (_c *mockclient_listMonitors_Call) Run(run func(ctx context.Context, o ...datadogV1.ListMonitorsOptionalParameters)) *mockclient_listMonitors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []datadogV1.ListMonitorsOptionalParameters
		var variadicArgs []datadogV1.ListMonitorsOptionalParameters
		if len(args) > 1 {
			variadicArgs = args[1].([]datadogV1.ListMonitorsOptionalParameters)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockclient_listMonitors_Call) Return(monitors []datadogV1.Monitor, response *http.Response, err error) *mockclient_listMonitors_Call {
	_c.Call.Return(monitors, response, err)
	return _c
}

func (_c *mockclient_listMonitors_Call) RunAndReturn(run func(ctx context.Context, o ...datadogV1.ListMonitorsOptionalParameters) ([]datadogV1.Monitor, *http.Response, error)) *mockclient_listMonitors_Call {
	_c.Call.Return(run)
	return _c
}

// withAuth provides a mock function for the type mockclient
func (_mock *mockclient) withAuth(ctx context.Context) context.Context {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for withAuth")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// mockclient_withAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'withAuth'
type mockclient_withAuth_Call struct {
	*mock.Call
}

// withAuth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockclient_Expecter) withAuth(ctx interface{}) *mockclient_withAuth_Call {
	return &mockclient_withAuth_Call{Call: _e.mock.On("withAuth", ctx)}
}

func (_c *mockclient_withAuth_Call) Run(run func(ctx context.Context)) *mockclient_withAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockclient_withAuth_Call) Return(context1 context.Context) *mockclient_withAuth_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *mockclient_withAuth_Call) RunAndReturn(run func(ctx context.Context) context.Context) *mockclient_withAuth_Call {
	_c.Call.Return(run)
	return _c
}
