// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dd

import (
	"context"
	"net/http"

	"github.com/DataDog/datadog-api-client-go/v2/api/datadog"
	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV1"
	mock "github.com/stretchr/testify/mock"
)

// newMockclient creates a new instance of mockclient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclient {
	mock := &mockclient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclient is an autogenerated mock type for the client type
type mockclient struct {
	mock.Mock
}

type mockclient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclient) EXPECT() *mockclient_Expecter {
	return &mockclient_Expecter{mock: &_m.Mock}
}

// GetDashboard provides a mock function for the type mockclient
func (_mock *mockclient) GetDashboard(ctx context.Context, dashboardId string) (datadogV1.Dashboard, *http.Response, error) {
	ret := _mock.Called(ctx, dashboardId)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboard")
	}

	var r0 datadogV1.Dashboard
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (datadogV1.Dashboard, *http.Response, error)); ok {
		return returnFunc(ctx, dashboardId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) datadogV1.Dashboard); ok {
		r0 = returnFunc(ctx, dashboardId)
	} else {
		r0 = ret.Get(0).(datadogV1.Dashboard)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *http.Response); ok {
		r1 = returnFunc(ctx, dashboardId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, dashboardId)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockclient_GetDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboard'
type mockclient_GetDashboard_Call struct {
	*mock.Call
}

// GetDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboardId string
func (_e *mockclient_Expecter) GetDashboard(ctx interface{}, dashboardId interface{}) *mockclient_GetDashboard_Call {
	return &mockclient_GetDashboard_Call{Call: _e.mock.On("GetDashboard", ctx, dashboardId)}
}

func (_c *mockclient_GetDashboard_Call) Run(run func(ctx context.Context, dashboardId string)) *mockclient_GetDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockclient_GetDashboard_Call) Return(dashboard datadogV1.Dashboard, response *http.Response, err error) *mockclient_GetDashboard_Call {
	_c.Call.Return(dashboard, response, err)
	return _c
}

func (_c *mockclient_GetDashboard_Call) RunAndReturn(run func(ctx context.Context, dashboardId string) (datadogV1.Dashboard, *http.Response, error)) *mockclient_GetDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonitor provides a mock function for the type mockclient
func (_mock *mockclient) GetMonitor(ctx context.Context, monitorId int64, o ...datadogV1.GetMonitorOptionalParameters) (datadogV1.Monitor, *http.Response, error) {
	var tmpRet mock.Arguments
	if len(o) > 0 {
		tmpRet = _mock.Called(ctx, monitorId, o)
	} else {
		tmpRet = _mock.Called(ctx, monitorId)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMonitor")
	}

	var r0 datadogV1.Monitor
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...datadogV1.GetMonitorOptionalParameters) (datadogV1.Monitor, *http.Response, error)); ok {
		return returnFunc(ctx, monitorId, o...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...datadogV1.GetMonitorOptionalParameters) datadogV1.Monitor); ok {
		r0 = returnFunc(ctx, monitorId, o...)
	} else {
		r0 = ret.Get(0).(datadogV1.Monitor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, ...datadogV1.GetMonitorOptionalParameters) *http.Response); ok {
		r1 = returnFunc(ctx, monitorId, o...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, ...datadogV1.GetMonitorOptionalParameters) error); ok {
		r2 = returnFunc(ctx, monitorId, o...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockclient_GetMonitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonitor'
type mockclient_GetMonitor_Call struct {
	*mock.Call
}

// GetMonitor is a helper method to define mock.On call
//   - ctx context.Context
//   - monitorId int64
//   - o ...datadogV1.GetMonitorOptionalParameters
func (_e *mockclient_Expecter) GetMonitor(ctx interface{}, monitorId interface{}, o ...interface{}) *mockclient_GetMonitor_Call {
	return &mockclient_GetMonitor_Call{Call: _e.mock.On("GetMonitor",
		append([]interface{}{ctx, monitorId}, o...)...)}
}

func (_c *mockclient_GetMonitor_Call) Run(run func(ctx context.Context, monitorId int64, o ...datadogV1.GetMonitorOptionalParameters)) *mockclient_GetMonitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []datadogV1.GetMonitorOptionalParameters
		var variadicArgs []datadogV1.GetMonitorOptionalParameters
		if len(args) > 2 {
			variadicArgs = args[2].([]datadogV1.GetMonitorOptionalParameters)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockclient_GetMonitor_Call) Return(monitor datadogV1.Monitor, response *http.Response, err error) *mockclient_GetMonitor_Call {
	_c.Call.Return(monitor, response, err)
	return _c
}

func (_c *mockclient_GetMonitor_Call) RunAndReturn(run func(ctx context.Context, monitorId int64, o ...datadogV1.GetMonitorOptionalParameters) (datadogV1.Monitor, *http.Response, error)) *mockclient_GetMonitor_Call {
	_c.Call.Return(run)
	return _c
}

// ListDashboards provides a mock function for the type mockclient
func (_mock *mockclient) ListDashboards(ctx context.Context, o ...datadogV1.ListDashboardsOptionalParameters) (datadogV1.DashboardSummary, *http.Response, error) {
	var tmpRet mock.Arguments
	if len(o) > 0 {
		tmpRet = _mock.Called(ctx, o)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListDashboards")
	}

	var r0 datadogV1.DashboardSummary
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...datadogV1.ListDashboardsOptionalParameters) (datadogV1.DashboardSummary, *http.Response, error)); ok {
		return returnFunc(ctx, o...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...datadogV1.ListDashboardsOptionalParameters) datadogV1.DashboardSummary); ok {
		r0 = returnFunc(ctx, o...)
	} else {
		r0 = ret.Get(0).(datadogV1.DashboardSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...datadogV1.ListDashboardsOptionalParameters) *http.Response); ok {
		r1 = returnFunc(ctx, o...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ...datadogV1.ListDashboardsOptionalParameters) error); ok {
		r2 = returnFunc(ctx, o...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockclient_ListDashboards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDashboards'
type mockclient_ListDashboards_Call struct {
	*mock.Call
}

// ListDashboards is a helper method to define mock.On call
//   - ctx context.Context
//   - o ...datadogV1.ListDashboardsOptionalParameters
func (_e *mockclient_Expecter) ListDashboards(ctx interface{}, o ...interface{}) *mockclient_ListDashboards_Call {
	return &mockclient_ListDashboards_Call{Call: _e.mock.On("ListDashboards",
		append([]interface{}{ctx}, o...)...)}
}

func (_c *mockclient_ListDashboards_Call) Run(run func(ctx context.Context, o ...datadogV1.ListDashboardsOptionalParameters)) *mockclient_ListDashboards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []datadogV1.ListDashboardsOptionalParameters
		var variadicArgs []datadogV1.ListDashboardsOptionalParameters
		if len(args) > 1 {
			variadicArgs = args[1].([]datadogV1.ListDashboardsOptionalParameters)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockclient_ListDashboards_Call) Return(dashboardSummary datadogV1.DashboardSummary, response *http.Response, err error) *mockclient_ListDashboards_Call {
	_c.Call.Return(dashboardSummary, response, err)
	return _c
}

func (_c *mockclient_ListDashboards_Call) RunAndReturn(run func(ctx context.Context, o ...datadogV1.ListDashboardsOptionalParameters) (datadogV1.DashboardSummary, *http.Response, error)) *mockclient_ListDashboards_Call {
	_c.Call.Return(run)
	return _c
}

// ListMonitors provides a mock function for the type mockclient
func (_mock *mockclient) ListMonitors(ctx context.Context, o ...datadogV1.ListMonitorsOptionalParameters) ([]datadogV1.Monitor, *http.Response, error) {
	var tmpRet mock.Arguments
	if len(o) > 0 {
		tmpRet = _mock.Called(ctx, o)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListMonitors")
	}

	var r0 []datadogV1.Monitor
	var r1 *http.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...datadogV1.ListMonitorsOptionalParameters) ([]datadogV1.Monitor, *http.Response, error)); ok {
		return returnFunc(ctx, o...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...datadogV1.ListMonitorsOptionalParameters) []datadogV1.Monitor); ok {
		r0 = returnFunc(ctx, o...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datadogV1.Monitor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...datadogV1.ListMonitorsOptionalParameters) *http.Response); ok {
		r1 = returnFunc(ctx, o...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ...datadogV1.ListMonitorsOptionalParameters) error); ok {
		r2 = returnFunc(ctx, o...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockclient_ListMonitors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMonitors'
type mockclient_ListMonitors_Call struct {
	*mock.Call
}

// ListMonitors is a helper method to define mock.On call
//   - ctx context.Context
//   - o ...datadogV1.ListMonitorsOptionalParameters
func (_e *mockclient_Expecter) ListMonitors(ctx interface{}, o ...interface{}) *mockclient_ListMonitors_Call {
	return &mockclient_ListMonitors_Call{Call: _e.mock.On("ListMonitors",
		append([]interface{}{ctx}, o...)...)}
}

func (_c *mockclient_ListMonitors_Call) Run(run func(ctx context.Context, o ...datadogV1.ListMonitorsOptionalParameters)) *mockclient_ListMonitors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []datadogV1.ListMonitorsOptionalParameters
		var variadicArgs []datadogV1.ListMonitorsOptionalParameters
		if len(args) > 1 {
			variadicArgs = args[1].([]datadogV1.ListMonitorsOptionalParameters)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockclient_ListMonitors_Call) Return(monitors []datadogV1.Monitor, response *http.Response, err error) *mockclient_ListMonitors_Call {
	_c.Call.Return(monitors, response, err)
	return _c
}

func (_c *mockclient_ListMonitors_Call) RunAndReturn(run func(ctx context.Context, o ...datadogV1.ListMonitorsOptionalParameters) ([]datadogV1.Monitor, *http.Response, error)) *mockclient_ListMonitors_Call {
	_c.Call.Return(run)
	return _c
}

// getDDClient provides a mock function for the type mockclient
func (_mock *mockclient) getDDClient() *datadog.APIClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getDDClient")
	}

	var r0 *datadog.APIClient
	if returnFunc, ok := ret.Get(0).(func() *datadog.APIClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datadog.APIClient)
		}
	}
	return r0
}

// mockclient_getDDClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDDClient'
type mockclient_getDDClient_Call struct {
	*mock.Call
}

// getDDClient is a helper method to define mock.On call
func (_e *mockclient_Expecter) getDDClient() *mockclient_getDDClient_Call {
	return &mockclient_getDDClient_Call{Call: _e.mock.On("getDDClient")}
}

func (_c *mockclient_getDDClient_Call) Run(run func()) *mockclient_getDDClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclient_getDDClient_Call) Return(aPIClient *datadog.APIClient) *mockclient_getDDClient_Call {
	_c.Call.Return(aPIClient)
	return _c
}

func (_c *mockclient_getDDClient_Call) RunAndReturn(run func() *datadog.APIClient) *mockclient_getDDClient_Call {
	_c.Call.Return(run)
	return _c
}

// withAuth provides a mock function for the type mockclient
func (_mock *mockclient) withAuth(ctx context.Context) context.Context {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for withAuth")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// mockclient_withAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'withAuth'
type mockclient_withAuth_Call struct {
	*mock.Call
}

// withAuth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockclient_Expecter) withAuth(ctx interface{}) *mockclient_withAuth_Call {
	return &mockclient_withAuth_Call{Call: _e.mock.On("withAuth", ctx)}
}

func (_c *mockclient_withAuth_Call) Run(run func(ctx context.Context)) *mockclient_withAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockclient_withAuth_Call) Return(context1 context.Context) *mockclient_withAuth_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *mockclient_withAuth_Call) RunAndReturn(run func(ctx context.Context) context.Context) *mockclient_withAuth_Call {
	_c.Call.Return(run)
	return _c
}
