name: Link validation

on:
  workflow_call:
# TODO
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

env:
  DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator:latest # TODO: set version

jobs:
  link-validator:
    name: link-validator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Link validation
        id: lnk
        env:
          LOG_LEVEL: "debug"
#          FILE_MASKS: "*.md"
          LOOKUP_PATH: "."
          PAT: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: "https://github.com"
        shell: bash
        run: |
          pwd
          ls -l 
          echo "----"
          docker run --rm -e LOG_LEVEL -e FILE_MASKS -e LOOKUP_PATH -e PAT -e AWS_ENV  -e BASE_URL ${DOCKER_VALIDATOR}



