name: Link validation
on:
  workflow_call:
  # TODO
  workflow_dispatch:
#  pull_request:
#    branches:
#      - master
#      - main

env:
  DOCKER_IMAGE_NAME: ghcr.io/your-ko/link-validator:0.5.0
jobs:
  link-validator:
    name: link-validator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Check image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: Dockerfile
          build-args: |
            VERSION="0.0.0"
            BUILD_DATE=${{ steps.meta.outputs.BUILD_DATE }}
            GIT_COMMIT=${{ steps.meta.outputs.GIT_COMMIT }}
          tags: ${{ env.DOCKER_IMAGE_NAME }}:test
          provenance: false
          push: false
      - name: Run Link validation
        id: lnk
        env:
          LOG_LEVEL: "debug"
          FILE_MASKS: "*.md,*.yaml"
          LOOKUP_PATH: "."
          PAT: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: "https://google.com"
        shell: bash
        run: |
          docker run --rm \
            -e LOG_LEVEL \
            -e FILE_MASKS \
            -e LOOKUP_PATH \
            -e PAT \
            -e BASE_URL \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            ${{ env.DOCKER_IMAGE_NAME }}:test
