name: link-validator-workflow.yml

on:
  workflow_call:
# TODO
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

env:
  DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator:latest # TODO: set version

jobs:
  link-validator:
    name: link-validator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run Link validation
        id: lnk
        env:
          FILE_MASKS: "*.md"
          LOOKUP_PATH: "."
          PAT: ${{ secrets.PAT }}
          BASE_URL: "https://github.com"
        shell: bash
        run: |
          docker run --rm -e FILE_MASKS -e LOOKUP_PATH -e PAT -e AWS_ENV  -e BASE_URL ${DOCKER_VALIDATOR}



