name: Link validation
on:
  push:
    branches:
      - master
      - main

env:
  DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator:0.18.0

jobs:
  link-validator:
    name: link-validator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Run Link validation
        id: lnk
        env:
          LV_LOG_LEVEL: "info"
          LV_FILE_MASKS: "*.md"
          LV_PAT: ${{ secrets.GITHUB_TOKEN }}
          LV_CORP_PAT: ${{ secrets.GITHUB_TOKEN }}
          LV_CORP_URL: ""
        shell: bash
        run: |
          env | grep -E '^LV_' > .env
          docker run --rm \
            --env-file .env \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            ${{env.DOCKER_VALIDATOR}}
