name: Link validation
on:
  workflow_call:
  # TODO
  workflow_dispatch:
env:
  DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator:0.14.0
jobs:
  link-validator:
    name: link-validator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run Link validation
        id: lnk
        env:
          LOG_LEVEL: "debug"
          FILE_MASKS: "*.md,*.yaml"
          FILE_LIST: "*"
          LOOKUP_PATH: "."
          EXCLUDE_PATH: "/test"
          PAT: ${{ secrets.GITHUB_TOKEN }}
          CORP_PAT: ${{ secrets.GITHUB_TOKEN }}
          CORP_URL: "https://github.com"
        shell: bash
        run: |
          docker run --rm \
            -e LOG_LEVEL \
            -e FILE_MASKS \
            -e LOOKUP_PATH \
            -e EXCLUDE_PATH \
            -e FILE_LIST \
            -e PAT \
            -e CORP_PAT \
            -e CORP_URL \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            ${DOCKER_VALIDATOR}
