name: Link validation
on:
  push:
    branches:
      - main

env:
  DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator:0.16.0
jobs:
  link-validator:
    name: link-validator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run Link validation
        id: lnk
        env:
          LOG_LEVEL: "debug"
          FILE_MASKS: "*.md"
          FILE_LIST: "*"
          LOOKUP_PATH: "."
          EXCLUDE_PATH: "/test"
          PAT: ${{ secrets.GITHUB_TOKEN }}
          CORP_PAT: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          docker run --rm \
            -e LOG_LEVEL \
            -e FILE_MASKS \
            -e PAT \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            ${DOCKER_VALIDATOR}
