name: Link validation
on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  DOCKER_VALIDATOR: ghcr.io/your-ko/link-validator:0.18.0

jobs:
  link-validator:
    name: link-validator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Link validation
        id: lnk
        env:
          LV_LOG_LEVEL: "info"
          LV_FILE_MASKS: "*.md"
          LV_PAT: ${{ secrets.GITHUB_TOKEN }}
          LV_CORP_PAT: ${{ secrets.GITHUB_TOKEN }}
          LV_CORP_URL: ""
        shell: bash
        run: |
          DOCKER_ENV_ARGS=""
          for var in $(env | grep '^LV_' | cut -d'=' -f1); do
            DOCKER_ENV_ARGS="$DOCKER_ENV_ARGS -e $var"
          done
          
          docker run --rm \
                 $DOCKER_ENV_ARGS \
                 -v "${{ github.workspace }}:/work" \
                 -w /work \
                 ${{env.DOCKER_VALIDATOR}}
